In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

sns.set_theme(style="whitegrid")

RANDOM_STATE = 42

data_path = Path("Datasets/037")

files = [
    file
    for file in data_path.rglob("*")
    if file.is_file()
]

print("Number of files:", len(files))

for file in files:
    print(file)

gateways = pd.read_csv(
    data_path / "gateways.csv",
    sep=';',
    engine="python"
)

readings = pd.read_csv(
    data_path / "readings.csv",
    sep='\t',
    engine="python"
)

units = pd.read_csv(
    data_path / "units.csv",
    sep=',',
    engine="python"
)


datasets = {
    "gateways": gateways,
    "readings": readings,
    "units": units
}

for name, data in datasets.items():
    print(f"\n{name.upper()}")
    print("Shape:", data.shape)
    print("Columns:", data.columns.tolist())
    display(data.head())


print("Gateways:", gateways.shape)
print("Units:", units.shape)
print("Readings:", readings.shape)


print("Number of elements Gateway: ", gateways.shape[0])
print("Not Null cells in Gateways:", gateways.dropna().shape[0])
print("Number of elements Readings: ", readings.shape[0])
print("Not Null cells in readings: ",readings.dropna().shape[0])
print("Number of elements Units: ", units.shape[0])
print("Not Null cells in Units: ", units.dropna().shape[0])


#gateways[gateways.isnull().any(axis=1)]
#readings[readings.isnull().any(axis=1)]
units[units.isnull().any(axis=1)]

Number of files: 3
Datasets\037\gateways.csv
Datasets\037\readings.csv
Datasets\037\units.csv

GATEWAYS
Shape: (16000, 14)
Columns: ['vendor', 'gatewayId', 'lat', 'seen_last', 'ipv4', 'versionFirmware', 'Technician', 'id_unit', 'modelHardware', 'id_depot', 'macAddress', 'Lon', 'dbm_signal', 'date_install']

,vendor,gatewayId,lat,seen_last,ipv4,versionFirmware,Technician,id_unit,modelHardware,id_depot,macAddress,Lon,dbm_signal,date_install
0,"Holland, Moore and Foster",GW-00000,39.85515,25 Jan 2025,201.144.200.206,v3.4.1,Viviane Jopich,70.0,GWX-300,5,4b:57:9d:d8:85:7e,-8.87854,-67.0,2023-05-10
1,Castro Nascimento Lda.,GW-00001,39.97771,24 May 2024,162.167.208.12,v2.7.0,Klaus Peter Klemt-Klapp,463.0,GWX-200,67,28:1b:c1:bf:d2:72,-9.09701,-78.4,"04/18/2021, 00:00:00"
2,Green-Mitchell,GW-00002,39.68046,2024/10/21,214.16.189.57,v1.2.5,Steven Luna,759.0,NODE-9,109,2c:75:86:3d:87:96,-8.56949,-73.9,2021-10-22
3,Stey Fechner GbR,GW-00003,40.37614,09 Jul 2024,250.7.67.70,v3.4.1,Adriana Pinho,1966.0,GWX-100,31,50:33:0f:fe:aa:b6,-9.20827,-84.9,25 Apr 2021
4,Misicher Nette GmbH & Co. KGaA,GW-00004,40.07243,"10/24/2024, 00:00:00",225.244.98.178,v3.4.1,Mark Hines,457.0,NODE-7,34,01:f9:49:1a:95:c1,-6.35564,-71.6,2015/04/14

READINGS
Shape: (12618, 14)
Columns: ['id_unit', 'ts_cycle', 'motorCurrent', 'filter_dp', 'oilTemperature', 'pressure_reservoir', 'pressure_working', 'pressureOil', 'vibrationRms', 'flowmeter', 'intake_humidity', 'ambientNoise', 'bearingTemp', 'failure']

,id_unit,ts_cycle,motorCurrent,filter_dp,oilTemperature,pressure_reservoir,pressure_working,pressureOil,vibrationRms,flowmeter,intake_humidity,ambientNoise,bearingTemp,failure
0,U01130,"02/10/2023, 17:12:00",4.36969,28.64924,49.67845,7.34282,7.31041,2.31187,4.99789,30.25891,66.67165,72.94257,64.95347,0
1,U00848,18 Sep 2023,4.22091,23.03530,41.77282,8.50849,8.53387,3.60240,1.87873,30.49048,89.24165,85.55312,74.46724,0
2,U00943,2023/12/29,2.80830,44.64527,69.78227,9.84619,9.70007,4.82881,4.49602,31.08300,80.81591,74.80889,60.05191,0
3,U01894,"11/12/2023, 15:24:00",4.45080,23.51547,47.49275,10.08831,10.00805,4.95817,2.15054,24.19140,17.74420,78.35942,67.82175,0
4,U00083,18 Nov 2023,3.97643,17.19827,70.25846,7.86674,7.88600,2.37735,4.11747,26.91899,19.60671,66.19757,59.54418,0

UNITS
Shape: (2000, 7)
Columns: ['Manufacturer', 'class_duty', 'id_unit', 'lastOverhaul', 'lineCode', 'id_depot', 'hoursService']

,Manufacturer,class_duty,id_unit,lastOverhaul,lineCode,id_depot,hoursService
0,Jäkel,L,1,05 Dec 2019,L6,12,13856.6
1,"Clark, Jackson and Anderson",H,2,"03/19/2023, 00:00:00",L4,109,14557.4
2,Pinto,1,3,2020-09-28,L6,26,15652.8
3,Fleming Group,N,4,2023/11/30,L6,68,NaN
4,Pinto,heavy,5,26 Feb 2018,L3,102,6141.3

Gateways: (16000, 14)
Units: (2000, 7)
Readings: (12618, 14)
Number of elements Gateway:  16000
Not Null cells in Gateways: 2000
Number of elements Readings:  12618
Not Null cells in readings:  11003
Number of elements Units:  2000
Not Null cells in Units:  1900

,Manufacturer,class_duty,id_unit,lastOverhaul,lineCode,id_depot,hoursService
3,Fleming Group,N,4,2023/11/30,L6,68,NaN
17,Rocha,N,18,"11/08/2024, 00:00:00",L1,72,NaN
28,Fleming Group,H,29,"08/29/2021, 00:00:00",L6,66,NaN
53,"Holland, Moore and Foster",heavy,54,"09/19/2023, 00:00:00",L3,108,NaN
65,Meister,2,66,23 Jan 2023,L5,26,NaN
67,Wiek Dörr GbR,L,68,2020-10-29,L6,15,NaN
74,Morales Ltd,1,75,"02/01/2018, 00:00:00",L3,28,NaN
76,Martinez-Smith,med,77,2016/05/11,L5,54,NaN
87,Horton-Huffman,L,88,2016/11/11,L3,39,NaN
99,Marquez Group,normal,100,11 Dec 2024,L2,69,NaN
232,"Jones, Russell and Guzman",2,233,14 Apr 2019,L2,64,NaN
289,Barth Gute OHG mbH,L,290,02 Mar 2018,L4,3,NaN
293,Higgins Inc,med,294,10 Mar 2022,L2,73,NaN
302,Stey Fechner GbR,heavy,303,"08/14/2019, 00:00:00",L2,103,NaN
304,Jones Group,med,305,2022/06/06,L4,57,NaN
307,Torres Melo Lda.,normal,308,2016/02/02,L4,71,NaN
336,Morales Ltd,3,337,"06/21/2023, 00:00:00",L3,74,NaN
353,Börner Klemt KG,normal,354,"04/02/2017, 00:00:00",L3,61,NaN
383,Gierschner GmbH & Co. OHG,normal,384,27 May 2018,L5,63,NaN
392,Green-Mitchell,N,393,"05/13/2021, 00:00:00",L5,75,NaN
397,Misicher Nette GmbH & Co. KGaA,1,398,"10/21/2018, 00:00:00",L3,87,NaN
400,Striebitz AG,1,401,2019/11/14,L2,90,NaN
422,Morales Ltd,2,423,2015-05-18,L5,77,NaN
439,Esteves S/A,2,440,2019/12/26,L2,73,NaN
447,Jäkel,normal,448,05 Sep 2021,L2,47,NaN
453,Ladeck,med,454,2022/11/14,L1,61,NaN
465,Nette Weller Stiftung & Co. KGaA,L,466,31 Aug 2018,L4,27,NaN
497,"Clark, Jackson and Anderson",med,498,2019/12/19,L1,63,NaN
649,Pinto,1,650,2018/11/09,L3,22,NaN
685,Esteves S/A,normal,686,"05/30/2021, 00:00:00",L5,110,NaN
694,"Clark, Jackson and Anderson",1,695,2016/01/16,L4,8,NaN
700,Meister,med,701,"04/27/2020, 00:00:00",L5,37,NaN
709,Castro Nascimento Lda.,N,710,2019-11-06,L5,48,NaN
723,Tran-Lewis,N,724,11 Sep 2020,L6,51,NaN
738,Ladeck Junk KG,2,739,24 Aug 2020,L3,106,NaN
743,Meister,normal,744,2016-12-08,L2,90,NaN
760,Hamann GmbH & Co. KGaA,1,761,"08/13/2018, 00:00:00",L3,75,NaN
770,Sousa S/A,normal,771,2020/05/04,L1,50,NaN
782,Jäkel,light,783,2024-08-15,L1,25,NaN
805,Salazar-Harris,med,806,2017/01/01,L5,47,NaN
809,Hamann GmbH & Co. KGaA,1,810,2015/01/25,L2,11,NaN
847,Higgins Inc,light,848,2022-06-03,L3,27,NaN
870,"Clark, Jackson and Anderson",1,871,23 Feb 2018,L5,5,NaN
887,"Clark, Jackson and Anderson",med,888,2023-10-06,L6,64,NaN
906,Jäkel,2,907,2024-02-11,L6,56,NaN
937,"Clark, Jackson and Anderson",1,938,10 Dec 2023,L2,28,NaN
954,"Jones, Russell and Guzman",2,955,11 Jan 2016,L6,53,NaN
959,Torres Melo Lda.,3,960,2017/05/07,L5,55,NaN
965,Striebitz AG,normal,966,22 Oct 2023,L2,48,NaN
971,Tran-Lewis,H,972,06 Jun 2015,L6,105,NaN
996,Jäkel,heavy,997,"10/16/2018, 00:00:00",L6,101,NaN
1048,Sousa S/A,L,1049,2024/09/09,L2,22,NaN
1060,Hein Dörr GmbH,N,1061,04 May 2016,L4,50,NaN
1071,"Holland, Moore and Foster",2,1072,2019-01-30,L6,41,NaN
1073,Pinto,med,1074,2017/03/19,L4,58,NaN
1087,Castro Nascimento Lda.,heavy,1088,"01/02/2018, 00:00:00",L6,35,NaN
1124,Gierschner GmbH & Co. OHG,H,1125,2022/04/01,L4,113,NaN
1131,Misicher Nette GmbH & Co. KGaA,3,1132,2020-09-13,L6,96,NaN
1185,Börner Klemt KG,3,1186,2016/08/23,L2,114,NaN
1200,Misicher Nette GmbH & Co. KGaA,L,1201,2018-02-11,L6,3,NaN
1201,Hunt LLC,2,1202,2019-01-04,L2,46,NaN
1211,Horton-Huffman,normal,1212,2017-06-12,L4,50,NaN
1216,Moreira Henriques S.A.,med,1217,03 Mar 2023,L6,75,NaN
1286,Castro Nascimento Lda.,H,1287,2018-12-01,L5,115,NaN
1335,Morales Ltd,1,1336,2018/12/16,L3,36,NaN
1401,"Smith, Richardson and Johnson",1,1402,2019/08/30,L2,22,NaN
1432,Hamann GmbH & Co. KGaA,1,1433,"01/23/2021, 00:00:00",L1,7,NaN
1452,Misicher Nette GmbH & Co. KGaA,heavy,1453,2019-04-25,L6,113,NaN
1483,Moreira Henriques S.A.,N,1484,2022-05-10,L3,84,NaN
1544,Stey Fechner GbR,heavy,1545,2022-11-23,L2,82,NaN
1566,Fleming Group,med,1567,"05/21/2017, 00:00:00",L6,117,NaN
1577,"Clark, Jackson and Anderson",heavy,1578,2020/09/19,L1,96,NaN
1582,Green-Mitchell,N,1583,"11/30/2022, 00:00:00",L5,72,NaN
1592,Jones Group,med,1593,"07/27/2021, 00:00:00",L4,93,NaN
1593,Powell Inc,N,1594,06 Jul 2023,L3,44,NaN
1595,Pinto,L,1596,2017-03-08,L5,38,NaN
1597,Barth Gute OHG mbH,med,1598,2021/10/21,L4,54,NaN
1622,Schulz Weiß GmbH,L,1623,2021/11/14,L4,35,NaN
1631,Horton-Huffman,1,1632,"04/30/2017, 00:00:00",L6,18,NaN
1705,"Clark, Jackson and Anderson",H,1706,2017-07-28,L2,114,NaN
1741,Pinto,normal,1742,2020/08/30,L1,57,NaN
1768,Wiek Dörr GbR,2,1769,2021/08/08,L4,30,NaN
1780,Schulz Weiß GmbH,L,1781,02 Mar 2021,L4,16,NaN
1786,Morales Ltd,heavy,1787,03 Jul 2016,L3,70,NaN
1828,Martinez-Smith,med,1829,2021-12-27,L3,42,NaN
1845,Rocha,N,1846,2019-08-29,L5,61,NaN
1861,Moreira Henriques S.A.,N,1862,27 Apr 2015,L5,65,NaN
1872,Börner Klemt KG,1,1873,"07/14/2018, 00:00:00",L1,17,NaN
1884,Sousa S/A,normal,1885,2019-02-11,L2,54,NaN
1915,Nette Weller Stiftung & Co. KGaA,1,1916,"01/07/2021, 00:00:00",L1,19,NaN
1922,Jones Group,heavy,1923,"07/24/2017, 00:00:00",L6,101,NaN
1924,Jäkel,light,1925,2019/02/05,L2,44,NaN
1938,Ladeck,N,1939,23 Apr 2022,L6,57,NaN
1943,"Jones, Russell and Guzman",L,1944,"04/20/2024, 00:00:00",L3,13,NaN
1959,Misicher Nette GmbH & Co. KGaA,H,1960,2019-07-29,L1,119,NaN
1967,Pinto,1,1968,2022-04-21,L1,25,NaN
1984,Higgins Inc,med,1985,2021/11/18,L4,70,NaN
1986,Meister,med,1987,"04/28/2018, 00:00:00",L4,58,NaN
1994,Hein Dörr GmbH,3,1995,"08/01/2023, 00:00:00",L2,7,NaN
1996,Jäkel,1,1997,2016-01-26,L5,22,NaN

In [ ]:
#Every file has different seperator, In Gateways.csv seperator is a semicolon (';'), in Reading.csv seperator is a Tab ('\t'), in Units.csv seperator is a comma (',')

#Problems:
# In Gateways.csv date formats of seen_last, date_install colomns are different

In [20]:
gateways.isna().sum()

vendor                 0
gatewayId              0
lat                    0
seen_last              0
ipv4                   0
versionFirmware        0
Technician             0
id_unit            14000
modelHardware          0
id_depot               0
macAddress             0
Lon                    0
dbm_signal             0
date_install           0
dtype: int64

In [ ]:
#in Gatewaydataset

In [18]:
readings.isna().sum()

id_unit                 0
ts_cycle                0
motorCurrent            0
filter_dp             531
oilTemperature          0
pressure_reservoir      0
pressure_working        0
pressureOil             0
vibrationRms          488
flowmeter               0
intake_humidity       673
ambientNoise            0
bearingTemp             0
failure                 0
dtype: int64

In [19]:
units.isna().sum()

Manufacturer      0
class_duty        0
id_unit           0
lastOverhaul      0
lineCode          0
id_depot          0
hoursService    100
dtype: int64

In [21]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    df.info()

GATEWAYS
<class 'pandas.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   vendor           16000 non-null  str
 1   gatewayId        16000 non-null  str
 2   lat              16000 non-null  float64
 3   seen_last        16000 non-null  str
 4   ipv4             16000 non-null  str
 5   versionFirmware  16000 non-null  str
 6   Technician       16000 non-null  str
 7   id_unit          2000 non-null   float64
 8   modelHardware    16000 non-null  str
 9   id_depot         16000 non-null  int64
 10  macAddress       16000 non-null  str
 11  Lon              16000 non-null  float64
 12  dbm_signal       16000 non-null  float64
 13  date_install     16000 non-null  str
dtypes: float64(4), int64(1), str(9)
memory usage: 3.3 MB

READINGS
<class 'pandas.DataFrame'>
RangeIndex: 12618 entries, 0 to 12617
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_unit             12618 non-null  str
 1   ts_cycle            12618 non-null  str
 2   motorCurrent        12618 non-null  float64
 3   filter_dp           12087 non-null  float64
 4   oilTemperature      12618 non-null  float64
 5   pressure_reservoir  12618 non-null  float64
 6   pressure_working    12618 non-null  float64
 7   pressureOil         12618 non-null  float64
 8   vibrationRms        12130 non-null  float64
 9   flowmeter           12618 non-null  float64
 10  intake_humidity     11945 non-null  float64
 11  ambientNoise        12618 non-null  float64
 12  bearingTemp         12618 non-null  float64
 13  failure             12618 non-null  int64
dtypes: float64(11), int64(1), str(2)
memory usage: 1.6 MB

UNITS
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Manufacturer  2000 non-null   str
 1   class_duty    2000 non-null   str
 2   id_unit       2000 non-null   int64
 3   lastOverhaul  2000 non-null   str
 4   lineCode      2000 non-null   str
 5   id_depot      2000 non-null   int64
 6   hoursService  1900 non-null   float64
dtypes: float64(1), int64(2), str(4)
memory usage: 173.2 KB

In [23]:
gateways.describe()

                lat      id_unit      id_depot           Lon    dbm_signal
count  16000.000000  2000.000000  16000.000000  16000.000000  16000.000000
mean      40.142132  1000.500000     59.246750     -7.753390    -69.955081
std        0.897981   577.494589     34.553675      0.889109      9.975559
min       38.600140     1.000000      0.000000     -9.299770   -108.700000
25%       39.363568   500.750000     29.000000     -8.521795    -76.700000
50%       40.144035  1000.500000     59.000000     -7.752610    -69.800000
75%       40.912925  1500.250000     89.000000     -6.987493    -63.200000
max       41.699970  2000.000000    119.000000     -6.200010    -40.000000